//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BichoDenunciaService.AppCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class midia
    {
        public int id { get; set; }
        public Nullable<int> id_denuncia { get; set; }
        public Nullable<int> sequencia { get; set; }
        public string tipo_midia { get; set; }
        public byte[] arquivo { get; set; }
    
        public virtual denuncia denuncia { get; set; }
    }
}
